AdminPanelPecApi/Models/NewsEvent.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdminPanelPecApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NewsEvent
    {
        public long ID { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public Nullable<long> StatusID { get; set; }
        public string ImageUrl { get; set; }
        public long CreatedBy { get; set; }
        public long LastUpdatedBy { get; set; }
        public System.DateTime LastUpdatedAt { get; set; }
        public long RecordStatus { get; set; }
    }
}

AdminPanelPecApi/Models/NewsEventsViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace AdminPanelPecApi.Models
{
    public class NewsEventsViewModel
    {
        public long ID { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public Nullable<long> StatusID { get; set; }
        public string ImageUrl { get; set; }
        public long CreatedBy { get; set; }
        public long LastUpdatedBy { get; set; }
        public System.DateTime LastUpdatedAt { get; set; }
        public long RecordStatus { get; set; }
    }
}

AdminPanelPecApi/Controllers/NewsEventController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Web.Http;
using System.Web.Http.Description;
using AdminPanelPecApi.Models;
using System.IO;
using System.Web;

namespace AdminPanelPecApi.Controllers
{
    public class NewsEventController : ApiController
    {
        private ComplaintsPortalEntities db = new ComplaintsPortalEntities();

        // GET: api/NewsEventsApi
        public IQueryable<NewsEvent> GetNewsEvents()
        {
            return db.NewsEvents;
        }

        // GET: api/NewsEventsApi/5
        [ResponseType(typeof(NewsEvent))]
        public IHttpActionResult GetNewsEvent(long id)
        {
            NewsEvent newsEvent = db.NewsEvents.Find(id);
            if (newsEvent == null)
            {
                return NotFound();
            }

            return Ok(newsEvent);
        }

        // PUT: api/NewsEventsApi/5
        [ResponseType(typeof(void))]
        public IHttpActionResult PutNewsEvent(long id, NewsEvent newsEvent)
        {
            if (!ModelState.IsValid)
            {
                return BadRequest(ModelState);
            }

            if (id != newsEvent.ID)
            {
                return BadRequest();
            }

            db.Entry(newsEvent).State = EntityState.Modified;

            try
            {
                db.SaveChanges();
            }
            catch (DbUpdateConcurrencyException)
            {
                if (!NewsEventExists(id))
                {
                    return NotFound();
                }
                else
                {
                    throw;
                }
            }

            return StatusCode(HttpStatusCode.NoContent);
        }

        // POST: api/NewsEventsApi
        [ResponseType(typeof(NewsEvent))]
        public IHttpActionResult PostNewsEvent(NewsEvent newsEvent)
        {
            newsEvent.CreatedBy = 1;
            newsEvent.CreatedDate = DateTime.Now.Date;
            newsEvent.LastUpdatedAt = DateTime.Now.Date;
            newsEvent.LastUpdatedBy = 1;
            newsEvent.RecordStatus = 1;
            newsEvent.StatusID = 1;
           
            if (!ModelState.IsValid)
            {
                return BadRequest(ModelState);
            }

            //if (Request.Files.Count > 0)
            //{
            //    var file = Request.Files[0];
            //    if (file != null && file.ContentLength > 0)
            //    {
            //        string filename = Path.GetFileName(file.FileName);
            //        string path = Path.Combine(Server.MapPath("~/uploads/"), filename);
            //        file.SaveAs(path);
            //        newsEvent.ImageUrl = filename;
            //    }
            //}
                //int uploadedFiles = 0;


                string path = HttpContext.Current.Server.MapPath("~/uploads/");
            if (!Directory.Exists(path))
            {
                Directory.CreateDirectory(path);
            }
            //
            if (HttpContext.Current.Request.Files.AllKeys.Any())
            {
                var fileupload = HttpContext.Current.Request.Files[0];
                if (fileupload != null)
                {
                    var saveImage = Path.Combine(HttpContext.Current.Server.MapPath("~/uploads/"), fileupload.FileName);
                    fileupload.SaveAs(saveImage);
                    newsEvent.ImageUrl = saveImage.ToString();
                }
            }

            //HttpFileCollection httpFilesRequest = HttpContext.Current.Request.Files;
            //for (int i = 0; i <= 1; i++)
            //{
            //    HttpPostedFile postedFile = httpFilesRequest[i];
            //    if (postedFile.ContentLength > 0)
            //    {
            //        if (!File.Exists(path + Path.GetFileName(postedFile.FileName)))
            //        {
            //            postedFile.SaveAs(path + Path.GetFileName(postedFile.FileName));
            //            uploadedFiles = uploadedFiles + 1;
            //            newsEvent.ImageUrl = postedFile.FileName;
            //        }
            //    }
            //}
            //if (uploadedFiles > 0)
            //{
            //    db.NewsEvents.Add(newsEvent);
            //    db.SaveChanges();
            //}
            //return CreatedAtRoute("DefaultApi", new { id = newsEvent.ID }, newsEvent);

            //HttpResponseMessage result = null;
            //var httpRequest = HttpContext.Current.Request;
            //if (httpRequest.Files.Count > 0)
            //{
            //    var file = httpRequest.Files[0];
            //    if (file != null && file.ContentLength > 0)
            //    {
            //        string filename = file.FileName;
            //        string path = HttpContext.Current.Server.MapPath("~/uploads/" + filename);
            //        file.SaveAs(path);
            //        newsEvent.ImageUrl = filename;
            //    }


            //}
            db.NewsEvents.Add(newsEvent);
            db.SaveChanges();

            return CreatedAtRoute("DefaultApi", new { id = newsEvent.ID }, newsEvent);

            //return CreatedAtRoute("DefaultApi", new { id = newsEvent.ID }, newsEvent);
        }

        // DELETE: api/NewsEventsApi/5
        [ResponseType(typeof(NewsEvent))]
        public IHttpActionResult DeleteNewsEvent(long id)
        {
            NewsEvent newsEvent = db.NewsEvents.Find(id);
            if (newsEvent == null)
            {
                return NotFound();
            }

            db.NewsEvents.Remove(newsEvent);
            db.SaveChanges();

            return Ok(newsEvent);
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }

        private bool NewsEventExists(long id)
        {
            return db.NewsEvents.Count(e => e.ID == id) > 0;
        }
    }
}

AdminPanelPecApi/Controllers/NewsEventsController.cs
using AdminPanelPecApi.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Http;
using System.Web;
using System.Web.Mvc;

namespace AdminPanelPecApi.Controllers
{
    public class NewsEventsController : Controller
    {
        ApiResults apiResult = new ApiResults();
        // GET: NewsEvents
        public ActionResult Index()
        {
            return View(apiResult.GetNewsEventList());
        }

        public ActionResult Create()
        {
            return View();
        }
        [HttpPost]
        public JsonResult Create(NewsEvent NewsEventData)
        {
            int response;
            if (apiResult.InsertNewsEventRecord(NewsEventData))
            {
                return Json(response = 1, JsonRequestBehavior.AllowGet);
            }
            return Json(response = 0, JsonRequestBehavior.AllowGet);
        }
        public ActionResult Details(long id)
        {
           
            return View(apiResult.GetNewsEventDetails(id));
        }

        public ActionResult Edit(long id)
        {
           
            return View(apiResult.GetNewsEventEditDetail(id));
        }
        [HttpPost]
        public JsonResult Edit(long id, NewsEvent editNewsEvent)
        {
            
                int response;
            if (apiResult.SaveNewsEventEditedRecord(id,editNewsEvent))
            {
                return Json(response = 1, JsonRequestBehavior.AllowGet);
            }
            return Json(response = 0, JsonRequestBehavior.AllowGet);
        }

        public ActionResult Delete(long id)
        {
            int response;
            if (apiResult.DeleteNewsEventRecord(id))
            {
                return Json(response = 1, JsonRequestBehavior.AllowGet);
            }
            return Json(response = 0, JsonRequestBehavior.AllowGet);
        }
    }
}

AdminPanelPecApi/Views/NewsEvents/Create.cshtml
@model AdminPanelPecApi.Models.NewsEvent

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<script src="~/Content/Application Scripts/NewsEvents.js"></script>
<div class="BodyMargin">

    @using (Html.BeginForm("Create", "NewsEvents", FormMethod.Post, new { enctype = "multipart/form-data" ,@id="newsEventForm"}))
    {
        @Html.AntiForgeryToken()

        <div class="form-horizontal">
            <h4>NewsEvent</h4>
            <hr />
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })

            <div class="form-group">
                <div class="row">

                    <div class="col-lg-2">
                        @Html.LabelFor(model => model.Title, htmlAttributes: new { @class = "control-label col-md-2" })
                    </div>
                    <div class="col-lg-8">
                        @Html.EditorFor(model => model.Title, new { htmlAttributes = new { @class = "form-control", @placeholder = "Title" } })
                        @Html.ValidationMessageFor(model => model.Title, "", new { @class = "text-danger" })
                    </div>
                </div>
            </div>

            <div class="form-group">
                <div class="row">
                    <div class="col-lg-2">
                        @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
                    </div>
                    <div class="col-lg-8">
                        @*@Html.TextAreaFor(model => model.Description, new { htmlAttributes = new { @class = "form-control",@placeholder="Description" } })*@
                        @Html.TextAreaFor(model => model.Description, new { htmlAttributes = new { @class = "form-control", @placeholder = "Description" } })
                        @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
                    </div>
                </div>
            </div>

            <div class="form-group">
                <div class="row">
                    <div class="col-lg-2">
                        @*@Html.LabelFor(model => model.ImageUrl, htmlAttributes: new { @class = "control-label col-md-2" })*@
                        <label>Image</label>
                    </div>
                    <div class="col-lg-2">
                        @*@Html.EditorFor(model => model.ImageUrl, new { htmlAttributes = new { @class = "form-control" } })*@
                        @*<img id="blah" src="" height="100px" width="100px" />*@
                        @*@Html.ValidationMessageFor(model => model.ImageUrl, "", new { @class = "text-danger" })*@
                        <input type='file' id="fileUpload" onchange="readURL(this);" />

                    </div>
                    <div class="col-lg-1"></div>
                    <div class="col-lg-7">


                    </div>
                </div>
            </div>

            <div class="form-group">
                <div class="row">
                    <div class="col-lg-2"></div>
                    <div class="col-lg-2">
                        <a class="btn-custom saveCreate" title="Save News/Event">Create</a>
                        @*<input type="submit" value="Create" class="btn btn-custom" />*@
                        <a href="/NewsEvents/Index/" class="btn-custom" title="View NewsEvents">Back</a>
                    </div>
                </div>

            </div>
        </div>
    }
</div>
<script>
    function readURL(input) {
        if (input.files && input.files[0]) {
            var reader = new FileReader();

            reader.onload = function (e) {
                $('#blah')
                    .attr('src', e.target.result);
            };

            reader.readAsDataURL(input.files[0]);
        }
    }
</script>

AdminPanelPecApi/Views/NewsEvents/Details.cshtml
@model AdminPanelPecApi.Models.NewsEvent

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}


<div class="BodyMargin">
    <h2>Details</h2>

    <div>
        <h4>NewsEvent</h4>
        <hr />


        <div class="form-group">
            <div class="row">
                <div class="col-lg-2">
                    <label>Title</label>
                </div>
                <div class="col-lg-6">
                    @Html.DisplayFor(model => model.Title)
                </div>
            </div>
        </div>
        <div class="form-group">
            <div class="row">
                <div class="col-lg-2">
                    <label>Description</label>
                </div>
                <div class="col-lg-6">
                    @Html.DisplayFor(model => model.Description)
                </div>
            </div>
        </div>

        <div class="form-group">
            <div class="row">

                <div class="col-lg-2">
                    <label>Image</label>
                </div>
                <div class="col-lg-4">
                    <img src="~/uploads/@Model.ImageUrl" height="100px" width="100px" />
                </div>
            </div>
        </div>
    </div>
    <div class="form-group">
        <div class="row">
            <div class="col-lg-2"></div>
            <div class="col-lg-2">
                <p>
                    <a href="/NewsEvents/Edit/@Model.ID" class="btn-custom" title="Edit Event">Edit</a>
                    @* @Html.ActionLink("Edit", "Edit", new { id = Model.ID }) |*@
                    @*@Html.ActionLink("Back to List", "Index")*@
                    <a href="/NewsEvents/Index/" class="btn-custom" title="Views Event">Back</a>
                </p>
            </div>
        </div>
    </div>

</div>

AdminPanelPecApi/Views/NewsEvents/Edit.cshtml
@model AdminPanelPecApi.Models.NewsEvent

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<script src="~/Content/Application Scripts/NewsEvents.js"></script>
<div class="BodyMargin">
    <h2>Edit</h2>

    @using (Html.BeginForm("Edit", "NewsEvents", FormMethod.Post, new { enctype = "multipart/form-data" }))
    {
        @Html.AntiForgeryToken()

        <div class="form-horizontal">
            <h4>NewsEvent</h4>
            <hr />
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            @Html.HiddenFor(model => model.ID)



            <div class="form-group">
                <div class="row">

                    <div class="col-lg-2">
                        @Html.LabelFor(model => model.Title, htmlAttributes: new { @class = "control-label col-md-2" })
                    </div>
                    <div class="col-lg-8">
                        @Html.EditorFor(model => model.Title, new { htmlAttributes = new { @class = "form-control", @placeholder = "Title" } })
                        @Html.ValidationMessageFor(model => model.Title, "", new { @class = "text-danger" })
                    </div>
                </div>
            </div>

            <div class="form-group">
                <div class="row">
                    <div class="col-lg-2">
                        @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
                    </div>
                    <div class="col-lg-8">
                        @Html.TextAreaFor(model => model.Description, new { htmlAttributes = new { @class = "form-control", @placeholder = "Description" } })
                        @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
                    </div>
                </div>
            </div>

            <div class="form-group">
                <div class="row">
                    <div class="col-lg-2">
                        <label>Image</label>
                    </div>
                    <div class="col-lg-6">
                        @*@Html.EditorFor(model => model.ImageUrl, new { htmlAttributes = new { @class = "form-control" } })*@
                        @*<img id="blah" src="" height="100px" width="100px" />*@
                        @*@Html.ValidationMessageFor(model => model.ImageUrl, "", new { @class = "text-danger" })*@
                        <img src="~/uploads/@Model.ImageUrl" height="50px" width="50px" />
                        <input type='file' name="file" onchange="readURL(this);" />
                    </div>
                    <div class="col-lg-4"></div>
                </div>
            </div>

            <div class="form-group">
                <div class="row">
                    <div class="col-lg-2"></div>
                    <div class="col-lg-2">
                        <input type="submit" value="Save" class="btn-custom submitButtonPadding" />
                        <a href="/NewsEvents/Index/" class="btn-custom" title="Views Event">Back</a>
                    </div>
                </div>
            </div>
        </div>
    }
</div>

AdminPanelPecApi/Views/NewsEvents/Index.cshtml
@model IEnumerable<AdminPanelPecApi.Models.NewsEvent>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<script src="~/Content/Application Scripts/NewsEvents.js"></script>
<div class="BodyMargin">
    <div class="row">
        <div class="col-lg-4">
            <label>News&amp;Events</label>

        </div>
        <div class="col-lg-8">
            <a href="/NewsEvents/Create/" class="rightFloat btn-custom" title="Add Event">New</a>

        </div>

    </div>
    <table id="NewsEventsData" class="table table-striped table-bordered">
        <thead>
            <tr>
                <th>Title</th>
                <th>Details</th>
                @*<th>Image</th>*@
                <th>Action</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {
                <tr>

                    <td>
                        @Html.DisplayFor(modelItem => item.Title)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Description)
                    </td>
                    @*<td>
                            <img src="~/uploads/@item.ImageUrl" height="20px" width="20px" />
                        </td>*@
                    <td>
                        @*@Html.ActionLink("Edit", "Edit", new { id = item.ID })*@
                        <a href='@Url.Action("Details", "NewsEvents",new { id=item.ID })'>
                            <img src="~/img/view.png" class="table_icon_Link" />
                        </a>
                        <a href='@Url.Action("Edit", "NewsEvents",new { id=item.ID })'>
                            <img src="~/img/edit.png" class="table_icon_Link" />
                        </a>
                        <a class="deleteEvent" data-toggle='modal' data-target='#DeleteModel' value="@item.ID"  href='@Url.Action("Delete", "NewsEvents",new { id=item.ID })'>
                            <img src="~/img/delete.png" class="table_icon_Link" />
                        </a>

                    </td>
                </tr>
            }
        </tbody>
        <tfoot>
        </tfoot>


    </table>

</div>
<!--****************** Delete PopUp Model ********************  -->

<div class="modal" tabindex="-1" id="DeleteModel" role="dialog">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <label class="modal-title">News&Event</label>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <label>Are You Sure, You Want to Delete News&Event?</label>
                <input type="hidden" id="DeletedRow" name="DeletedRow">
            </div>
            <div class="modal-footer">
                <button id="DeleteButton" type="button" class="btn btn-secondary">Yes</button>
                <button type="button" class="btn btn-secondary" data-dismiss="modal">No</button>
            </div>
        </div>
    </div>
</div>