AdminPanelPecApi/Models/FAQ.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdminPanelPecApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FAQ
    {
        public long ID { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string Statement { get; set; }
        public string Answer { get; set; }
        public int Category { get; set; }
        public long CreatedBy { get; set; }
        public long LastUpdatedBy { get; set; }
        public System.DateTime LastUpdatedAt { get; set; }
        public long RecordStatus { get; set; }
    }
}

AdminPanelPecApi/Models/FaqViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace AdminPanelPecApi.Models
{
    public class FaqViewModel
    {
        public long ID { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string Statement { get; set; }
        public string Answer { get; set; }
        public int Category { get; set; }
        public string CreatedBy { get; set; }
        public long LastUpdatedBy { get; set; }
        public System.DateTime LastUpdatedAt { get; set; }
        public long RecordStatus { get; set; }
    }
}

AdminPanelPecApi/Controllers/FAQController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Web.Http;
using System.Web.Http.Description;
using AdminPanelPecApi.Models;

namespace AdminPanelPecApi.Controllers
{
    public class FAQController : ApiController
    {
        private ComplaintsPortalEntities db = new ComplaintsPortalEntities();

        // GET: api/FAQsApi
        public IQueryable<FAQ> GetFAQs()
        {
                return db.FAQs;
        }

        // GET: api/FAQsApi/5
        [ResponseType(typeof(FAQ))]
        public IHttpActionResult GetFAQ(long id)
        {
            FAQ fAQ = db.FAQs.Find(id);
            if (fAQ == null)
            {
                return NotFound();
            }

            return Ok(fAQ);
        }

        // PUT: api/FAQsApi/5
        [ResponseType(typeof(void))]
        public IHttpActionResult PutFAQ(long id, FAQ fAQ)
        {

            fAQ.CreatedDate = DateTime.Now.Date;
            fAQ.CreatedBy = 1;
            fAQ.LastUpdatedAt = DateTime.Now.Date;
            fAQ.LastUpdatedBy = 1;
            fAQ.Category = 1;
            if (!ModelState.IsValid)
            {
                return BadRequest(ModelState);
            }

            if (id != fAQ.ID)
            {
                return BadRequest();
            }

            db.Entry(fAQ).State = EntityState.Modified;

            try
            {
                db.SaveChanges();
            }
            catch (DbUpdateConcurrencyException)
            {
                if (!FAQExists(id))
                {
                    return NotFound();
                }
                else
                {
                    throw;
                }
            }

            return StatusCode(HttpStatusCode.NoContent);
        }

        // POST: api/FAQsApi
        [ResponseType(typeof(FAQ))]
        public IHttpActionResult PostFAQ(FAQ fAQ)
        {
            try
            {
                fAQ.CreatedDate = DateTime.Now.Date;
                fAQ.CreatedBy = 1;
                fAQ.LastUpdatedAt = DateTime.Now.Date;
                fAQ.LastUpdatedBy = 1;
                fAQ.Category = 1;

                if (!ModelState.IsValid)
                {
                    return BadRequest(ModelState);
                }

                db.FAQs.Add(fAQ);
                db.SaveChanges();
                return StatusCode(HttpStatusCode.OK);
                //return CreatedAtRoute("DefaultApi", new { id = fAQ.ID }, fAQ);
            }
            catch (Exception ex)
            {
                return StatusCode(HttpStatusCode.BadRequest);
            }
        }

        // DELETE: api/FAQsApi/5
        [ResponseType(typeof(FAQ))]
        public IHttpActionResult DeleteFAQ(long id)
        {
            FAQ fAQ = db.FAQs.Find(id);
            if (fAQ == null)
            {
                return NotFound();
            }

            db.FAQs.Remove(fAQ);
            db.SaveChanges();

            return Ok(fAQ);
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }

        private bool FAQExists(long id)
        {
            return db.FAQs.Count(e => e.ID == id) > 0;
        }
    }
}

AdminPanelPecApi/Controllers/FAQsController.cs
using AdminPanelPecApi.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace AdminPanelPecApi.Controllers
{
    public class FAQsController : Controller
    {
        ApiResults apiResult = new ApiResults();
        // GET: FAQs
        public ActionResult Index()
        {

            IEnumerable<FAQ> faqData = null;

            return View(apiResult.GetFaqList(faqData));
        }

        public ActionResult Create()
        {
            return View();
        }
        [HttpPost]
        //public ActionResult Create(FAQ newfaq)
        //{
        //    if (apiResult.InsertFaqRecord(newfaq))
        //    {
        //        return RedirectToAction("Index");
        //    }
        //    return View("Create");
        //}
        public JsonResult Create(FAQ newfaq)
        {
            int response;
            if (apiResult.InsertFaqRecord(newfaq))
            {
                return Json(response = 1, JsonRequestBehavior.AllowGet);
            }
            return Json(response = 0, JsonRequestBehavior.AllowGet);
        }
        public ActionResult Details(long id)
        {
            FAQ faqData = null;
            return View(apiResult.GetFaqDetails(id, faqData));
        }
        public ActionResult Edit(long id)
        {
            return View(apiResult.GetFaqEditDetail(id));
        }
        [HttpPost]
        //public ActionResult Edit(long id, FAQ editfaq)
        //{
        //    //HttpClient client = new HttpClient();
        //    //client.BaseAddress = new Uri("http://localhost:49942/api/FAQsApi");
        //    //var insertFaq = client.PutAsJsonAsync<FAQ>("FAQsApi?id=" + id.ToString(), editfaq);
        //    //insertFaq.Wait();
        //    //var saveRecord = insertFaq.Result;
        //    if (apiResult.SaveFaqEditedRecord(id,editfaq))
        //    {
        //        return RedirectToAction("Index");
        //    }
        //    else
        //    {
        //        ViewBag.message = "Record Not Found.";
        //    }
        //    return View(editfaq);
        //}

        public JsonResult Edit(long id, FAQ editfaq)
        {
            //HttpClient client = new HttpClient();
            //client.BaseAddress = new Uri("http://localhost:49942/api/FAQsApi");
            //var insertFaq = client.PutAsJsonAsync<FAQ>("FAQsApi?id=" + id.ToString(), editfaq);
            //insertFaq.Wait();
            //var saveRecord = insertFaq.Result;
            int response;
            if (apiResult.SaveFaqEditedRecord(id, editfaq))
            {
                return Json(response = 1, JsonRequestBehavior.AllowGet);
            }
            return Json(response = 0, JsonRequestBehavior.AllowGet);
        }
        //public ActionResult Delete(long id)
        //{
        //    //HttpClient client = new HttpClient();
        //    //client.BaseAddress = new Uri("http://localhost:49942/api/FAQsApi");
        //    //var DeleteFaq = client.DeleteAsync("FAQsApi?id=" + id.ToString());
        //    //DeleteFaq.Wait();
        //    //var DeleteData = DeleteFaq.Result;
        //    if (apiResult.DeleteFaqRecord(id))
        //    {
        //        return RedirectToAction("Index");
        //    }
        //    return View("Index");
        //}



        public JsonResult Delete(long id)
        {
            int response;
            //HttpClient client = new HttpClient();
            //client.BaseAddress = new Uri("http://localhost:49942/api/FAQsApi");
            //var DeleteFaq = client.DeleteAsync("FAQsApi?id=" + id.ToString());
            //DeleteFaq.Wait();
            //var DeleteData = DeleteFaq.Result;
            if (apiResult.DeleteFaqRecord(id))
            {
                return Json(response = 1, JsonRequestBehavior.AllowGet);
            }
            return Json(response = 0, JsonRequestBehavior.AllowGet);
        }
    }
}

AdminPanelPecApi/Views/FAQs/Create.cshtml
@model AdminPanelPecApi.Models.FAQ

@{
    ViewBag.Title = "Create";
}

<script src="~/Content/Application Scripts/FAQ.js"></script>
<div class="BodyMargin">

    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-horizontal">
            <h4>Add New FAQ</h4>
            <hr />
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })

            <div class="form-group">
                <div class="row">
                    <div class="col-lg-1"></div>
                        <div class="col-lg-1">
                            <label><b>Question</b></label>
                        </div>
                        <div class="col-lg-8">
                            @Html.EditorFor(model => model.Statement, new { htmlAttributes = new { @class = "form-control",@placeholder="Question" } })
                            @Html.ValidationMessageFor(model => model.Statement, "", new { @class = "text-danger" })
                        </div>

                    </div>
                @*@Html.LabelFor(model => model.Statement, htmlAttributes: new { @class = "control-label col-md-2" })*@
            </div>

            <div class="form-group">
                <div class="row">
                    <div class="col-lg-1"></div>
                    <div class="col-lg-1">
                        <label><b>Answer</b></label>
                    </div>
                    <div class="col-lg-8">
                        @Html.TextAreaFor(model => model.Answer, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Answer, "", new { @class = "text-danger" })
                    </div>

                </div>
            </div>

            <div class="form-group">
                <div class="row">
                    <div class="col-lg-2"></div>
                    <div class="col-lg-2">
                        @*<input type="submit" value="Create" class="btn btn-default saveCreate" />*@
                        <a class="btn-custom saveCreate" title="Save FAQ">Create</a>
                        <a href="/Faqs/Index/" class="btn-custom" title="View FAQs">Back</a>
                    </div>
                </div>

            </div>
            @*<div class="form-group">
                    <div class="col-md-offset-2 col-md-10">
                        <input type="submit" value="Create" class="btn btn-default" />
                    </div>
                </div>*@
        </div>
    }
</div>







@*<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>FAQ</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.CreatedDate, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.CreatedDate, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.CreatedDate, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Statement, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Statement, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Statement, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Answer, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Answer, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Answer, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Category, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Category, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Category, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CreatedBy, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.CreatedBy, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.CreatedBy, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.LastUpdatedBy, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.LastUpdatedBy, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.LastUpdatedBy, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.LastUpdatedAt, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.LastUpdatedAt, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.LastUpdatedAt, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.RecordStatus, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.RecordStatus, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.RecordStatus, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}*@

AdminPanelPecApi/Views/FAQs/Details.cshtml
@model AdminPanelPecApi.Models.FAQ

@{
    ViewBag.Title = "Details";
}

<div class="BodyMargin">
    <h2>Details</h2>

    <div>
        <h4>FAQ</h4>
        <hr />

        <div class="form-group">
            <div class="row">

                <div class="col-lg-2">
                    <label>Question</label>
                </div>
                <div class="col-lg-8">
                    @Html.DisplayFor(model => model.Statement)
                </div>
            </div>
        </div>

        <div class="form-group">
            <div class="row">

                <div class="col-lg-2">
                    <label>Answer</label>
                </div>
                <div class="col-lg-8">
                    @Html.DisplayFor(model => model.Answer)
                </div>
            </div>
        </div>
    </div>
    <div class="form-group">
        <div class="row">

            <div class="col-lg-2"></div>
            <div class="col-lg-2">
                <a href="/Faqs/Edit/@Model.ID" class="btn-custom" title="Edit FAQ">Edit</a>
                <a href="/Faqs/Index/" class="btn-custom" title="Views Event">Back</a>
            </div>
        </div>
    </div>
    @*<p>
            @Html.ActionLink("Edit", "Edit", new { id = Model.ID }) |
            @Html.ActionLink("Back to List", "Index")
        </p>*@
</div>

AdminPanelPecApi/Views/FAQs/Edit.cshtml
@model AdminPanelPecApi.Models.FAQ

@{
    ViewBag.Title = "Edit";
}
<script src="~/Content/Application Scripts/FAQ.js"></script>

<div class="BodyMargin">

    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-horizontal">
            <h4>Edit FAQ</h4>
            <hr />
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            @Html.HiddenFor(model => model.ID)


            <div class="form-group">
                <div class="row">
                    <div class="col-lg-1"></div>
                    <div class="col-lg-1">
                        <label><b>Question</b></label>
                    </div>
                    <div class="col-lg-8">
                        @Html.EditorFor(model => model.Statement, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Statement, "", new { @class = "text-danger" })
                    </div>

                </div>
                @*@Html.LabelFor(model => model.Statement, htmlAttributes: new { @class = "control-label col-md-2" })*@
            </div>

            <div class="form-group">
                <div class="row">
                    <div class="col-lg-1"></div>
                    <div class="col-lg-1">
                        <label><b>Answer</b></label>
                    </div>
                    <div class="col-lg-8">
                        @Html.TextAreaFor(model => model.Answer, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Answer, "", new { @class = "text-danger" })
                    </div>

                </div>
            </div>

            <div class="form-group">
                <div class="row">
                    <div class="col-lg-2"></div>
                    <div class="col-lg-2">
                            <input type="submit" value="Save" class="btn-custom submitButtonPadding saveEdit" />
                            <a href="/Faqs/Index/" class="btn-custom" title="View FAQs">Back</a>
                    </div>
                    <div class="col-lg-2">
                        <h1>@ViewBag.message</h1>
                    </div>
                    </div>

            </div>


        </div>
    }
</div>



@*<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>FAQ</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.ID)

        <div class="form-group">
            @Html.LabelFor(model => model.CreatedDate, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.CreatedDate, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.CreatedDate, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Statement, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Statement, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Statement, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Answer, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Answer, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Answer, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Category, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Category, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Category, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CreatedBy, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.CreatedBy, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.CreatedBy, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.LastUpdatedBy, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.LastUpdatedBy, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.LastUpdatedBy, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.LastUpdatedAt, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.LastUpdatedAt, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.LastUpdatedAt, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.RecordStatus, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.RecordStatus, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.RecordStatus, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}*@

AdminPanelPecApi/Views/FAQs/Index.cshtml
@model IEnumerable<AdminPanelPecApi.Models.FAQ>

@{
    ViewBag.Title = "Index";
}
<script src="~/Content/Application Scripts/FAQ.js"></script>

<div class="BodyMargin faqHeight">
    @*<label><b>Question</b></label>*@
    <div class="row">
        <div class="col-lg-4">
            <label><b>FAQs</b></label>

        </div>
        <div class="col-lg-8">
            <a href="/FAQs/Create/" class="rightFloat btn-custom NewcustomMargin" title="Add FAQ">New</a>
        </div>

    </div>
    @foreach (var item in Model)
            {
        <div>
            <div class="row">
                <div class="col-lg-11 faqQuestion">
                    @Html.DisplayFor(modelItem => item.Statement)
                </div>
                <div class="col-lg-1">
                    <a data-toggle="dropdown" class="pull-right dropdown-toggle">
                        <img src="~/img/dots.png">
                    </a>
                    <ul class="dropdown-menu pull-right" role="menu">
                        <li>
                            <a href='@Url.Action("Details", "FAQs",new { id=item.ID })'>
                                @*<img src="~/img/view.png" class="table_icon_Link" />*@
                            View
                            </a>
                        </li>
                        <li>
                            <a class="editEvent" value="@item.ID" href='@Url.Action("Edit", "FAQs",new { id=item.ID })'>
                                @*<img src="~/img/edit.png" class="table_icon_Link" />*@
                                Edit
                            </a>
                        </li>
                        <li>
                            <a class="deleteEvent" data-toggle='modal' data-target='#DeleteModel' value="@item.ID" href='@Url.Action("Delete", "FAQs",new { id=item.ID })'>
                                @*<img src="~/img/delete.png" class="table_icon_Link" />*@
                                Delete
                            </a>
                        </li>
                    </ul>
    @*<img class="showcrudMenu" src="~/img/dots.png" />*@
                </div>


            </div>
            <div class="row">

                <div class="col-lg-11 faqAnswer">
                   
                        @Html.DisplayFor(modelItem => item.Answer)
                 
                </div>
            </div>

        </div>
        @*<div class="col-lg-4">
                <a href='@Url.Action("Details", "FAQs",new { id=item.ID })'>
                    <img src="~/img/view.png" class="table_icon_Link" />
                </a>
                <a class="editEvent" value="@item.ID" href='@Url.Action("Edit", "FAQs",new { id=item.ID })'>
                    <img src="~/img/edit.png" class="table_icon_Link" />
                </a>
                <a class="deleteEvent" data-toggle='modal' data-target='#DeleteModel' value="@item.ID" href='@Url.Action("Delete", "FAQs",new { id=item.ID })'>
                    <img src="~/img/delete.png" class="table_icon_Link" />
                </a>
            </div>*@

        @*<div class="col-lg-1 no_right_padding crudMenu">
            <ul class="dropdown-menu pull-right" role="menu">
                <li>
                    <a href='@Url.Action("Details", "FAQs",new { id=item.ID })'>
                        <img src="~/img/view.png" class="table_icon_Link" />
                    </a>
                </li>
                <li>
                    <a class="editEvent" value="@item.ID" href='@Url.Action("Edit", "FAQs",new { id=item.ID })'>
                        <img src="~/img/edit.png" class="table_icon_Link" />
                    </a>
                </li>
                <li>
                    <a class="deleteEvent" data-toggle='modal' data-target='#DeleteModel' value="@item.ID" href='@Url.Action("Delete", "FAQs",new { id=item.ID })'>
                        <img src="~/img/delete.png" class="table_icon_Link" />
                    </a>
                </li>

            </ul>
        </div>*@
    }

</div>
<!--****************** Delete PopUp Model ********************  -->

<div class="modal" tabindex="-1" id="DeleteModel" role="dialog">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <label class="modal-title">FAQs</label>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <label>Are You Sure, You Want to Delete FAQ?</label>
                <input type="hidden" id="DeletedRow" name="DeletedRow">
            </div>
            <div class="modal-footer">
                <button id="DeleteButton" type="button" class="btn btn-secondary">Yes</button>
                <button type="button" class="btn btn-secondary" data-dismiss="modal">No</button>
            </div>
        </div>
    </div>
</div>