AdminPanelPecApi/Models/Complaint.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdminPanelPecApi.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Complaint
    {
        public long ID { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string Subject { get; set; }
        public string Message { get; set; }
        public long StatusID { get; set; }
        public string TrackingID { get; set; }
        public long CreatedBy { get; set; }
        public long LastUpdatedBy { get; set; }
        public System.DateTime LastUpdatedAt { get; set; }
        public long RecordStatus { get; set; }
    }
}

AdminPanelPecApi/Controllers/ComplaintController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Web.Http;
using System.Web.Http.Description;
using AdminPanelPecApi.Models;
using static AdminPanelPecApi.Enumerations.Enumeration;
using System.Threading.Tasks;
using System.Net.Mail;

namespace AdminPanelPecApi.Controllers
{
    public class ComplaintController : ApiController
    {
        private ComplaintsPortalEntities db = new ComplaintsPortalEntities();

        // GET: api/Complaint
        public IQueryable<Complaint> GetComplaints()
        {
            return db.Complaints;
        }

        // GET: api/Complaint/5
        [ResponseType(typeof(Complaint))]
        public IHttpActionResult GetComplaint(long id)
        {
            Complaint complaint = db.Complaints.Find(id);
            if (complaint == null)
            {
                return NotFound();
            }

            return Ok(complaint);
        }

        // PUT: api/Complaint/5
        [ResponseType(typeof(void))]
        public IHttpActionResult PutComplaint(long id, Complaint complaint)
        {
            if (!ModelState.IsValid)
            {
                return BadRequest(ModelState);
            }

            if (id != complaint.ID)
            {
                return BadRequest();
            }

            db.Entry(complaint).State = EntityState.Modified;

            try
            {
                db.SaveChanges();
            }
            catch (DbUpdateConcurrencyException)
            {
                if (!ComplaintExists(id))
                {
                    return NotFound();
                }
                else
                {
                    throw;
                }
            }

            return StatusCode(HttpStatusCode.NoContent);
        }
       
       
        // POST: api/Complaint
        [ResponseType(typeof(Complaint))]
        public IHttpActionResult PostComplaint(Complaint complaint)
        {
            complaint.CreatedDate = DateTime.Now.Date; //Current Date Time
            complaint.StatusID = (long)ComplaintStatus.Pending;
            complaint.LastUpdatedAt = DateTime.Now.Date; //Current Date Time
            complaint.LastUpdatedBy = 1; //ID from Session
            complaint.RecordStatus = 1; // Record Status
            complaint.CreatedBy = 1;
            
            if (!ModelState.IsValid)
            {
                return BadRequest(ModelState);
            }

            db.Complaints.Add(complaint);


            try
            {
                db.SaveChanges();
            }
            catch (DbUpdateException)
            {
                if (ComplaintExists(complaint.ID))
                {
                    return Conflict();
                }
                else
                {
                    throw;
                }
            }

            return CreatedAtRoute("DefaultApi", new { id = complaint.ID }, complaint);
        }

        // DELETE: api/Complaint/5
        [ResponseType(typeof(Complaint))]
        public IHttpActionResult DeleteComplaint(long id)
        {
            Complaint complaint = db.Complaints.Find(id);
            if (complaint == null)
            {
                return NotFound();
            }

            db.Complaints.Remove(complaint);
            db.SaveChanges();

            return Ok(complaint);
        }

   
        public IHttpActionResult GetTrackRecord(string search)
        {
            //try
            //{
                var complaint = db.Complaints.Where(x => x.TrackingID == search).ToList();
            if (complaint != null)
            {
                return Ok(complaint);
            }
            else
            {
                return NotFound();
            }
                //}
            //catch (Exception ex)
            //{
            //}

        }
        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }

        private bool ComplaintExists(long id)
        {
            return db.Complaints.Count(e => e.ID == id) > 0;
        }
    }
}

AdminPanelPecApi/Controllers/ComplaintsController.cs
using AdminPanelPecApi.Enumerations;
using AdminPanelPecApi.Models;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.IO;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Net.Mail;
using System.Web;
using System.Web.Mvc;

namespace AdminPanelPecApi.Controllers
{
    public class ComplaintsController : Controller
    {
        ComplaintsPortalEntities db = new ComplaintsPortalEntities();
        ApiResults apiResult = new ApiResults();
        // GET: Complaints
        public ActionResult Index()
        {
            //Complaint model = new Complaint();

            //IEnumerable<Complaint> ComplaintsData = null;
            // model.Compaints = 

            return View(apiResult.GetComplaintList());
        }
        public ActionResult Details(long id)
        {
            //Complaint complaintData = null;
            return View(apiResult.GetComplaintDetails(id));
        }
        public ActionResult Create()
        {
            return View();
        }
        [HttpPost]
        public JsonResult Create(Complaint newComplaint)
        {
            int response;
            if (apiResult.InsertComplaintRecord(newComplaint))
            {
                return Json(response = 1, JsonRequestBehavior.AllowGet);
            }
            return Json(response = 0, JsonRequestBehavior.AllowGet);
        }

        public ActionResult ComplaintStatus(string TrackingID)
        {

            return View(apiResult.SearchRecord(TrackingID));
        }
        
        public JsonResult SendEmail(EmailComplaintsViewModel emailData)
        {
            try
            {
                //var file = ConvertThisPageToPdf();
                var Subject = emailData.Subject;
                var Body = emailData.AdminComments + emailData.Message;
                var UserEmail = "alb191.akhaliq@gmail.com";
                var Password = "adi@03349681828";
                using (System.Net.Mail.MailMessage mm = new System.Net.Mail.MailMessage(UserEmail, emailData.ToEmail))
                {
                    mm.Subject = Subject;
                    string body = EmailBody(emailData);
                    //file Attachment If Required
                    //string[] code = body.Split('>');
                    //string codedigit = code[1];
                    //codedigit = codedigit.Substring(0, 4);
                    // string FilePath = link;
                    //Attachment attachment = new Attachment(ResolveUrl(FilePath));
                    //mm.Attachments.Add(attachment);
                    //Attachment at = new Attachment("C:\\Users\\AlberuniTech\\Downloads\\sample-file.pdf");
                    //mm.Attachments.Add(at);
                    mm.Body = body;
                    mm.IsBodyHtml = true;
                    SmtpClient smtp = new SmtpClient();
                    smtp.Host = "smtp.gmail.com";
                    smtp.UseDefaultCredentials = false;
                    smtp.EnableSsl = true;
                    NetworkCredential NetworkCred = new NetworkCredential("alb191.akhaliq@gmail.com", "adi@03349681828");
                    smtp.Credentials = NetworkCred;
                    smtp.Port = 587;
                    smtp.Send(mm);
                    Complaint complaintStatus = db.Complaints.Find(emailData.ComplaintID);
                    complaintStatus.StatusID = (long)Enumeration.ComplaintStatus.Open;
                    complaintStatus.LastUpdatedAt = DateTime.Now.Date;
                    complaintStatus.LastUpdatedBy = 1;
                    complaintStatus.CreatedBy = 1;
                    db.Entry(complaintStatus).State = EntityState.Modified;
                    //db.SaveChanges();

                    Comment commentsData = new Comment();
                    commentsData.CreatedDate = DateTime.Now.Date;
                    commentsData.ComplaintID = emailData.ComplaintID;
                    commentsData.Comments = emailData.AdminComments;
                    commentsData.CreatedBy = 1;
                    commentsData.LastUpdatedAt = DateTime.Now.Date;
                    commentsData.LastUpdatedBy = 1;
                    commentsData.RecordStatus = 1;
                    db.Comments.Add(commentsData);
                    db.SaveChanges();

                    // System.IO.File.Delete(@"C:\\Users\\AlberuniTech\\Downloads\\sample-file.pdf");
                    return Json(1, JsonRequestBehavior.AllowGet);
                }
            }
            catch (Exception ex)
            {
                return Json(null, JsonRequestBehavior.AllowGet);
            }
        }
        private string EmailBody(EmailComplaintsViewModel emailData)

        {

            string body = string.Empty;
            //using streamreader for reading my htmltemplate   

            using (StreamReader reader = new StreamReader(Server.MapPath("~/DesignEmail/EmailTemplate.html")))

            {
                
                body = reader.ReadToEnd();

            }
            body = body.Replace("{AdminComments}", emailData.AdminComments);
            body = body.Replace("{TrackingID}", emailData.TrackingID);
            body = body.Replace("{Subject}", emailData.Subject); //replacing the required things
            body = body.Replace(" {Message}", emailData.Message);


            return body;

        }

        public ActionResult GetEmailRecord(long id)
        {
            Complaint complaint = db.Complaints.Find(id);
            return View(complaint);
        }
    }
}

AdminPanelPecApi/Views/Complaints/ComplaintStatus.cshtml
@model IEnumerable<AdminPanelPecApi.Models.Complaint>
@using AdminPanelPecApi.Enumerations
@{
    ViewBag.Title = "ComplaintStatus";
    Layout = "~/Views/Shared/_Layout.cshtml";
}




<div class="BodyMargin">
    @using (Html.BeginForm("ComplaintStatus", "Complaints", FormMethod.Get))
    {
        <div class="form-group">
            <div class="row">
                <div class="col-lg-2">
                    <label><b>Tracking ID</b></label>
                </div>
                <div class="col-lg-2">
                    <input type="text" name="trackingID" placeholder="Enter Tracking ID" />
                </div>
                <div class="col-lg-1">
                    <input type="submit" value="Search" name="Search" />
                </div>
            </div>
        </div>
    }

    @if (Model.Count() <= 0)
    {
        <label><b class="hideMessage">Record Doesn't Exist</b></label>
    }
    else
    {
        foreach (var item in Model)
        {


            <div class="form-group">
                <div class="row">

                    <div class="col-lg-2">
                        <label>Subject</label>
                    </div>
                    <div class="col-lg-8">
                        @Html.DisplayFor(modelItem => item.Subject)
                    </div>
                </div>
            </div>

            <div class="form-group">
                <div class="row">

                    <div class="col-lg-2">
                        <label>Message</label>
                    </div>
                    <div class="col-lg-8">
                        @Html.DisplayFor(modelItem => item.Message)
                    </div>
                </div>
            </div>
            <div class="form-group">
                <div class="row">
                    <div class="col-lg-2">
                        <label>Status</label>
                    </div>
                    <div class="col-lg-8">
                        @if (item.StatusID == 0)
                        {
                            <label><b>@Enumeration.ComplaintStatus.Pending</b></label>
                        }
                        @if (item.StatusID == 1)
                        {
                            <label><b>@Enumeration.ComplaintStatus.Open</b></label>
                        }
                        @if (item.StatusID == 2)
                        {
                            <label><b>@Enumeration.ComplaintStatus.Close</b></label>
                        }
                    </div>

                </div>
            </div>
                @*<p>
                        @Html.ActionLink("Edit", "Edit", new { id = Model.ID }) |
                        @Html.ActionLink("Back to List", "Index")
                    </p>*@

        }

    }
</div>

AdminPanelPecApi/Views/Complaints/Create.cshtml
@model AdminPanelPecApi.Models.Complaint

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<script src="~/Content/Application Scripts/Complaints.js"></script>
<h2>Create</h2>

    <div class="BodyMargin">

        @using (Html.BeginForm())
        {
            @Html.AntiForgeryToken()

            <div class="form-horizontal">
                <h4>Register Complaint</h4>
                <hr />
                @Html.ValidationSummary(true, "", new { @class = "text-danger" })

                <div class="form-group">
                    <div class="row">
                        <div class="col-lg-1"></div>
                        <div class="col-lg-1">
                            <label><b>Subject</b></label>
                        </div>
                        <div class="col-lg-8">
                            @Html.EditorFor(model => model.Subject, new { htmlAttributes = new { @class = "form-control", @placeholder = "Question" } })
                            @Html.ValidationMessageFor(model => model.Subject, "", new { @class = "text-danger" })
                        </div>

                    </div>
                    @*@Html.LabelFor(model => model.Statement, htmlAttributes: new { @class = "control-label col-md-2" })*@
                </div>

                <div class="form-group">
                    <div class="row">
                        <div class="col-lg-1"></div>
                        <div class="col-lg-1">
                            <label><b>Message</b></label>
                        </div>
                        <div class="col-lg-8">
                            @Html.TextAreaFor(model => model.Message, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.Message, "", new { @class = "text-danger" })
                        </div>

                    </div>
                </div>

                @*<div class="form-group">
                    <div class="row">
                        <div class="col-lg-1"></div>
                        <div class="col-lg-1">
                            <label><b>Comments</b></label>
                        </div>
                        <div class="col-lg-8">
                            @Html.TextAreaFor(model => model.Comments, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.Comments, "", new { @class = "text-danger" })
                        </div>

                    </div>*@
                </div>

                @*<div class="form-group">
                    <div class="row">
                        <div class="col-lg-1"></div>
                        <div class="col-lg-1">
                            <label><b>CNIC</b></label>
                        </div>
                        <div class="col-lg-8">
                            @Html.EditorFor(model => model.TrackingID, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.TrackingID, "", new { @class = "text-danger" })
                        </div>
                    </div>
                </div>*@

                <div class="form-group">
                    <div class="row">
                        <div class="col-lg-2"></div>
                        <div class="col-lg-2">
                            @*<input type="submit" value="Create" class="btn btn-default saveCreate" />*@
                            <a class="btn-custom registerComplaint" title="Register Complaint">Register</a>
                            <a href="/Complaints/Index/" class="btn-custom" title="View Complaints">Back</a>
                        </div>
                    </div>

                </div>
                @*<div class="form-group">
                        <div class="col-md-offset-2 col-md-10">
                            <input type="submit" value="Create" class="btn btn-default" />
                        </div>
                    </div>*@
            </div>
        }
    </div>

AdminPanelPecApi/Views/Complaints/Details.cshtml
@model AdminPanelPecApi.Models.Complaint

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<script src="~/Content/Application Scripts/Complaints.js"></script>
<div class="BodyMargin">
    <h2>Details</h2>

    <div>
        <h4>Compalints</h4>
        <hr />
        <div class="form-group">
            <div class="row">

                <div class="col-lg-2">
                    <label><b>Tracking ID</b></label>
                </div>
                <div class="col-lg-8">
                    @Html.DisplayFor(model => model.TrackingID)
                </div>
            </div>
        </div>

        <div class="form-group">
            <div class="row">

                <div class="col-lg-2">
                    <label> <b>Subject</b></label>
                </div>
                <div class="col-lg-8">
                    @Html.DisplayFor(model => model.Subject)
                </div>
            </div>
        </div>
        <div class="loader"></div>
        <div class="form-group">
            <div class="row">

                <div class="col-lg-2">
                    <label><b>Message</b></label>
                </div>
                <div class="col-lg-8">
                    @Html.DisplayFor(model => model.Message)
                </div>
            </div>
        </div>

        <div class="form-group">
            <div class="row">

                <div class="col-lg-2">
                    <label><b>Email</b></label>
                </div>
                <div class="col-lg-8">
                    @Html.DisplayFor(model => model.CreatedBy)
                </div>
            </div>
        </div>
        @*<div class="form-group">
            <div class="row">

                <div class="col-lg-2">
                    <label><b>Comments</b></label>
                </div>
                <div class="col-lg-8">
                    @Html.DisplayFor(model => model.Comments)
                </div>
            </div>
        </div>*@
    </div>
    <div class="form-group">
        <div class="row">

            <div class="col-lg-2"></div>
            <div class="col-lg-2">
                @*<a href="/Faqs/Edit/@Model.ID" class="btn-custom" title="Edit FAQ">Edit</a>*@
                <a class="SendEmailEvent btn-custom" data-toggle='modal' data-target='#EmailModel' id="ForwardEmailRow" value="@Model.ID" href="#" title="Forward Complaints">Forward</a>
                <a href="/Complaints/Index/" class="btn-custom" title="Views Complaints">Back</a>
            </div>
        </div>
    </div>
    @*<p>
            @Html.ActionLink("Edit", "Edit", new { id = Model.ID }) |
            @Html.ActionLink("Back to List", "Index")
        </p>*@
</div>
<!--******************************Email Forward Popup****************************************-->

<div class="modal" tabindex="-1" id="EmailModel" role="dialog">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <label class="modal-title">Forward Complaint</label>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <input type="hidden" id="ComplaintID" name="ForwardEmailRow">
                
                    
                <div class="row">
                    <div class="col-lg-2">
                        <label class="Model-label">TrackID</label>
                    </div>
                    <div class="col-lg-8">
                        <label class="Model-Data" id="TrackingID">@Model.TrackingID</label>
                        @*<input class="Model-form-control" disabled="disabled" readonly="readonly" id="TrackingID" value="@Model.TrackingID" name="forwardComments" />*@
                    </div>
                </div>
                <div class="row">
                    <div class="col-lg-2">
                        <label class="Model-label">Subject</label>
                    </div>
                    <div class="col-lg-8">
                        <label class="Model-Data" id="Subject">@Model.Subject</label>
                        @*<input class="Model-form-control" disabled="disabled" readonly="readonly" id="Subject" value="@Model.Subject" name="forwardComments" />*@
                    </div>
                </div>
                <div class="row">
                    <div class="col-lg-2">
                        <label class="Model-label">Message</label>
                    </div>
                    <div class="col-lg-9">
                        <label class="Model-Data">@Model.Message</label>
                        @*<input class="form-control" disabled="disabled" readonly="readonly" id="Message" value="@Model.Message" name="forwardComments" />*@
                    </div>
                </div>
                <div class="row">
                    <div class="col-lg-3">
                        <label class="Model-label">To</label>
                    </div>
                    <div class="col-lg-8">
                        <input class="Model-form-control" autocomplete="on" id="ToEmail" name="ToEmail" />
                    </div>
                </div>
                <div class="row">
                    <div class="col-lg-3">
                        <label class="Model-label">Comments</label>
                    </div>
                    <div class="col-lg-8">
                        <textarea class="form-control" id="AdminComments" name="forwardComments"></textarea>
                    </div>
                </div>
            </div>
            <div class="modal-footer">
                <button id="SendEmailButton" type="button" class="btn btn-secondary">Send Email</button>
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancel</button>
            </div>
        </div>
    </div>
</div>

<!--*********************************LOADER*****************************************-->

AdminPanelPecApi/Views/Complaints/Index.cshtml
@model IEnumerable<AdminPanelPecApi.Models.Complaint>
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";


    }

<script src="~/Content/Application Scripts/Complaints.js"></script>

<div class="BodyMargin">
    <div class="row">
        <div class="col-lg-4">
            <label><b>Complaints</b></label>

        </div>
        <div class="col-lg-8">
            @*<a href="/FAQs/Create/" class="rightFloat btn-custom" title="Add FAQ">New</a>*@
        </div>

    </div>
    <table id="ComplaintsData" class="table table-striped table-bordered">
        <thead>
            <tr>
                <th>Tracking ID</th>
                <th>Subject</th>
                <th>Message</th>
                @*<th>Email</th>*@
                <th>Action</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.TrackingID)
                    </td>
                    <td title="@item.Subject">
                        @*@Html.DisplayFor(modelItem => item.Subject)*@
                        @{
                            if (item.Subject.Length < 30)
                            {
                                @item.Subject;
                            }
                            else
                            {
                                @item.Subject.Substring(0, 30);
                            }
                        }
                       
                    </td>
                    <td title="@item.Message">
                        @*@Html.DisplayFor(modelItem => item.Message)*@
                        @{
                            if (item.Message.Length < 30)
                            {
                                @item.Message;
                            }
                            else
                            {
                                @item.Message.Substring(0, 30);
                            }
                        }
                       
                    </td>
                    @*<td>
                        @Html.DisplayFor(modelItem => item.CreatedBy)
                    </td>*@
                   
                    @*<td>
                            <img src="~/uploads/@item.ImageUrl" height="20px" width="20px" />
                        </td>*@
                    <td>
                        @*@Html.ActionLink("Edit", "Edit", new { id = item.ID })*@
                        <a href='@Url.Action("Details", "Complaints",new { id=item.ID })'>
                            <img src="~/img/view.png" class="table_icon_Link" />
                        </a>
                        @*<a href='@Url.Action("Mail", "Complaints",new { id=item.ID })'>*@
                         
                            @*id = item.ID;*@
                        @*href='@Url.Action("SendEmail", "Complaints", new { id = item.ID })'*@
                        @*class="SendEmailEvent" data-toggle='modal' data-target='#EmailModel' id="ForwardEmailRow" value="@item.ID"*@ 
                        @*<a href='@Url.Action("GetEmailRecord", "Complaints",new { id=item.ID })' >
                            <img src="~/img/email.png" class="table_icon_Link" />
                        </a>*@


                    </td>
                </tr>
            }
        </tbody>
        <tfoot>
        </tfoot>


    </table>

</div>
<!--******************************Email Forward Popup****************************************-->

<div class="modal" tabindex="-1" id="EmailModel" role="dialog">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <label class="modal-title">Forward Complaint</label>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <input type="hidden" id="ComplaintID" name="ForwardEmailRow">

               
                  @*  var modelData = Model.Where(x => x.ID == id).FirstOrDefault();*@
                
                <div class="row">
                    <div class="col-lg-2">
                        <label class="Model-label">TrackID</label>
                    </div>
                    <div class="col-lg-8">
                        <label class="Model-Data" id="TrackingID" value=""></label>
                        @*<input class="Model-form-control" disabled="disabled" readonly="readonly" id="TrackingID" value="@Model.TrackingID" name="forwardComments" />*@
                    </div>
                </div>
                <div class="row">
                    <div class="col-lg-2">
                        <label class="Model-label">Subject</label>
                    </div>
                    <div class="col-lg-8">
                        <label class="Model-Data" id="Subject"></label>
                        @*<input class="Model-form-control" disabled="disabled" readonly="readonly" id="Subject" value="@Model.Subject" name="forwardComments" />*@
                    </div>
                </div>
                <div class="row">
                    <div class="col-lg-2">
                        <label class="Model-label" id="Message">Message</label>
                    </div>
                    <div class="col-lg-9">
                        <label class="Model-Data" value=""></label>
                        @*<input class="form-control" disabled="disabled" readonly="readonly" id="Message" value="@Model.Message" name="forwardComments" />*@
                    </div>
                </div>

                <div class="row">
                    <div class="col-lg-3">
                        <label class="Model-label">To</label>
                    </div>
                    <div class="col-lg-8">
                        <input class="Model-form-control" autocomplete="on" id="ToEmail" name="ToEmail" />
                    </div>
                </div>
                <div class="row">
                    <div class="col-lg-3">
                        <label class="Model-label">Comments</label>
                    </div>
                    <div class="col-lg-8">
                        <textarea class="form-control" id="AdminComments" name="forwardComments"></textarea>
                    </div>
                </div>
            </div>
            <div class="modal-footer">
                <button id="SendEmailButton" type="button" class="btn btn-secondary">Send Email</button>
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancel</button>
            </div>
        </div>
    </div>
</div>