AdminPanelPecApi/Models/Feedback.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdminPanelPecApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Feedback
    {
        public long ID { get; set; }
        public long ComplaintID { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string Message { get; set; }
        public string FeedbackFileUrl { get; set; }
        public long CreatedBy { get; set; }
        public long LastUpdatedBy { get; set; }
        public System.DateTime LastUpdatedAt { get; set; }
        public long RecordStatus { get; set; }
    }
}

AdminPanelPecApi/Models/FeedbackViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace AdminPanelPecApi.Models
{
    public class FeedbackViewModel
    {
        public long ID { get; set; }
        public long ComplaintID { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string Message { get; set; }
        public string FeedbackFileUrl { get; set; }
        public string CreatedBy { get; set; }
        public long LastUpdatedBy { get; set; }
        public System.DateTime LastUpdatedAt { get; set; }
        public long RecordStatus { get; set; }
    }
}

AdminPanelPecApi/Controllers/FeedbackController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Web.Http;
using System.Web.Http.Description;
using AdminPanelPecApi.Models;

namespace AdminPanelPecApi.Controllers
{
    public class FeedbackController : ApiController
    {
        private ComplaintsPortalEntities db = new ComplaintsPortalEntities();

        // GET: api/FeedbacksApi
        public IQueryable<Feedback> GetFeedbacks()
        {
            return db.Feedbacks;
        }

        // GET: api/FeedbacksApi/5
        [ResponseType(typeof(Feedback))]
        public IHttpActionResult GetFeedback(long id)
        {
            Feedback feedback = db.Feedbacks.Find(id);
            if (feedback == null)
            {
                return NotFound();
            }

            return Ok(feedback);
        }

        // PUT: api/FeedbacksApi/5
        [ResponseType(typeof(void))]
        public IHttpActionResult PutFeedback(long id, Feedback feedback)
        {
            if (!ModelState.IsValid)
            {
                return BadRequest(ModelState);
            }

            if (id != feedback.ID)
            {
                return BadRequest();
            }

            db.Entry(feedback).State = EntityState.Modified;

            try
            {
                db.SaveChanges();
            }
            catch (DbUpdateConcurrencyException)
            {
                if (!FeedbackExists(id))
                {
                    return NotFound();
                }
                else
                {
                    throw;
                }
            }

            return StatusCode(HttpStatusCode.NoContent);
        }

        // POST: api/FeedbacksApi
        [ResponseType(typeof(Feedback))]
        public IHttpActionResult PostFeedback(Feedback feedback)
        {
            feedback.CreatedDate = DateTime.Now.Date;
            feedback.ComplaintID = 1;
            feedback.CreatedBy = 1;
            feedback.LastUpdatedAt = DateTime.Now.Date;
            feedback.LastUpdatedBy = 1;
            feedback.RecordStatus = 1;
            if (!ModelState.IsValid)
            {
                return BadRequest(ModelState);
            }

            db.Feedbacks.Add(feedback);
            db.SaveChanges();

            return CreatedAtRoute("DefaultApi", new { id = feedback.ID }, feedback);
        }

        // DELETE: api/FeedbacksApi/5
        [ResponseType(typeof(Feedback))]
        public IHttpActionResult DeleteFeedback(long id)
        {
            Feedback feedback = db.Feedbacks.Find(id);
            if (feedback == null)
            {
                return NotFound();
            }

            db.Feedbacks.Remove(feedback);
            db.SaveChanges();

            return Ok(feedback);
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }

        private bool FeedbackExists(long id)
        {
            return db.Feedbacks.Count(e => e.ID == id) > 0;
        }
    }
}

AdminPanelPecApi/Controllers/FeedbacksController.cs
using AdminPanelPecApi.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Http;
using System.Web;
using System.Web.Mvc;

namespace AdminPanelPecApi.Controllers
{
    public class FeedbacksController : Controller
    {
        ApiResults apiResult = new ApiResults();
        // GET: Feedbacks
        public ActionResult Index()
        {
            
            return View(apiResult.GetFeedbackList());
        }

        public ActionResult Details(long id)
        {
           
            return View(apiResult.GetFeedbackDetails(id));
        }
        public ActionResult Create()
        {
            return View();
        }
        [HttpPost]
        public JsonResult Create(Feedback Newfeedback)
        {
            int response;
            if (apiResult.InsertFeedbackRecord(Newfeedback))
            {
                return Json(response = 1, JsonRequestBehavior.AllowGet);
            }
            return Json(response = 0, JsonRequestBehavior.AllowGet);
        }
    }
}

AdminPanelPecApi/Views/Feedbacks/Create.cshtml
@model AdminPanelPecApi.Models.Feedback

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<script src="~/Content/Application Scripts/Feedback.js"></script>
<div class="BodyMargin">

    @using (Html.BeginForm("Create", "Feedback", FormMethod.Post, new { enctype = "multipart/form-data" }))
    {
        @Html.AntiForgeryToken()

        <div class="form-horizontal">
            <h4>NewsEvent</h4>
            <hr />
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })

            <div class="form-group">
                <div class="row">

                    <div class="col-lg-2">
                        @Html.LabelFor(model => model.Message, htmlAttributes: new { @class = "control-label col-md-2" })
                    </div>
                    <div class="col-lg-8">
                        @Html.TextAreaFor(model => model.Message, new { htmlAttributes = new { @class = "form-control", @placeholder = "Message" } })
                        @Html.ValidationMessageFor(model => model.Message, "", new { @class = "text-danger" })
                    </div>
                </div>
            </div>

            <div class="form-group">
                <div class="row">
                    <div class="col-lg-2">
                        @*@Html.LabelFor(model => model.ImageUrl, htmlAttributes: new { @class = "control-label col-md-2" })*@
                        <label>File</label>
                    </div>
                    <div class="col-lg-2">
                        @*@Html.EditorFor(model => model.ImageUrl, new { htmlAttributes = new { @class = "form-control" } })*@
                        @*<img id="blah" src="" height="100px" width="100px" />*@
                        @*@Html.ValidationMessageFor(model => model.ImageUrl, "", new { @class = "text-danger" })*@
                        <input type='file' id="FeedbackfileUpload" name="Feedbackfile" />

                    </div>
                    <div class="col-lg-1"></div>
                    <div class="col-lg-7">


                    </div>
                </div>
            </div>

            <div class="form-group">
                <div class="row">
                    <div class="col-lg-2"></div>
                    <div class="col-lg-2">
                        <a class="btn-custom saveCreate" title="Save Feedback">Create</a>
                        @*<input type="submit" value="Create" class="btn btn-custom" />*@
                        <a href="/Feedback/Index/" class="btn-custom" title="View Feedback">Back</a>
                    </div>
                </div>

            </div>
        </div>
    }
</div>

AdminPanelPecApi/Views/Feedbacks/Details.cshtml
@model AdminPanelPecApi.Models.Feedback

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="BodyMargin">
    <h2>Details</h2>

    <div>
        <h4>Feedback</h4>
        <hr />
        <div class="form-group">
            <div class="row">
                <div class="col-lg-2">
                    <label>Complainant</label>
                </div>
                <div class="col-lg-6">
                    <label>Complaint By (NAME) Here</label>
                    @*@Html.DisplayFor(model => model.ComplaintID)*@
                </div>
            </div>
        </div>
        <div class="form-group">
            <div class="row">
                <div class="col-lg-2">
                    <label>Feedback Message</label>
                </div>
                <div class="col-lg-6">
                    @Html.DisplayFor(model => model.Message)
                </div>
            </div>
        </div>

        <div class="form-group">
            <div class="row">

                <div class="col-lg-2">
                    <label>File</label>
                </div>
                <div class="col-lg-4">
                    @*<a href="#">File Link Here</a>*@
                    <a>@Model.FeedbackFileUrl</a>
                </div>
            </div>
        </div>
    </div>
    <div class="form-group">
        <div class="row">
            <div class="col-lg-2"></div>
            <div class="col-lg-2">
                <p>
                    @* @Html.ActionLink("Edit", "Edit", new { id = Model.ID }) |*@
                    @*@Html.ActionLink("Back to List", "Index")*@
                    <a href="/feedbacks/Index/" class="btn-custom" title="Views Feedbacks">Back</a>
                </p>
            </div>
        </div>
    </div>

</div>

AdminPanelPecApi/Views/Feedbacks/Index.cshtml
@model IEnumerable<AdminPanelPecApi.Models.Feedback>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}


<div class="BodyMargin">
    <div class="row">
        <div class="col-lg-4">
            <label>Feedback</label>

        </div>
        <div class="col-lg-8">
            @*<a href="/NewsEvents/Create/" class="rightFloat btn-custom" title="Add Event">New</a>*@
        </div>

    </div>
    <table id="FeedbackData" class="table table-striped table-bordered">
        <thead>
            <tr>
               @* <th>Complainant</th>*@
                <th>Message</th>
                <th>File</th>
                @*<th>Image</th>*@
                <th>Action</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {
                <tr>
                    @*<td>
                        @Html.DisplayFor(modelItem => item.ComplaintID)
                    </td>*@
                    <td>
                        @Html.DisplayFor(modelItem => item.Message)
                    </td>
                    <td>
                        @*@Html.DisplayFor(modelItem => item.FeedbackFileUrl)*@
                        <a href="#">@item.FeedbackFileUrl</a>
                    </td>
                    @*<td>
                            <img src="~/uploads/@item.ImageUrl" height="20px" width="20px" />
                        </td>*@
                    <td>
                        @*@Html.ActionLink("Edit", "Edit", new { id = item.ID })*@
                        <a href='@Url.Action("Details", "Feedbacks",new { id=item.ID })'>
                            <img src="~/img/view.png" class="table_icon_Link" />
                        </a>

                    </td>
                </tr>
            }
        </tbody>
        <tfoot>
        </tfoot>


    </table>

</div>